In [1]:
import pandas as pd

data = [[1,444,"abc"],
        [2,555,"def"],
        [3,666,"ghi"],
        [4,444,"xyz"]]

# data = {'col1':[1,2,3,4],
#         'col2':[444,555,666,444],
#         'col3':['abc','def','ghi','xyz']}   
type(data)

df = pd.DataFrame(data)
df

   0    1    2
0  1  444  abc
1  2  555  def
2  3  666  ghi
3  4  444  xyz

In [2]:
cols = ['col1', 'col2', 'col3']
df = pd.DataFrame(data,columns = ['col1', 'col2', 'col3'])
df

   col1  col2 col3
0     1   444  abc
1     2   555  def
2     3   666  ghi
3     4   444  xyz

In [6]:
df[cols] = df[cols].astype('category')

In [14]:
df.describe(include='category')

        col1  col2 col3
count      4     4    4
unique     4     3    4
top        1   444  abc
freq       1     2    1

In [15]:
classification = df.col2.unique()
classification

[444, 555, 666]
Categories (3, int64): [444, 555, 666]

In [ ]:
#df[cols] = df[cols].astype('int')

#df['col2'].min()

TypeError: Categorical is not ordered for operation min
you can use .as_ordered() to change the Categorical to an ordered one

In [16]:
def get_range(df):
    return df.max() - df.min()
get_range(df.col1)

TypeError: Categorical is not ordered for operation max
you can use .as_ordered() to change the Categorical to an ordered one