In [15]:
import pandas as pd

s = pd.Series([1,2,3,4])
s

0    1
1    2
2    3
3    4
dtype: int64

In [2]:
#specify the index
s = pd.Series([1,2,3,4], index = ["A", "B", "C", "D"])
s

A    1
B    2
C    3
D    4
dtype: int64

In [3]:
data = [[1,444,"abc"],
        [2,555,"def"],
        [3,666,"ghi"],
        [4,444,"xyz"]]

# data = {'col1':[1,2,3,4],
#         'col2':[444,555,666,444],
#         'col3':['abc','def','ghi','xyz']}   
type(data)

list

In [4]:
df = pd.DataFrame(data)
df

   0    1    2
0  1  444  abc
1  2  555  def
2  3  666  ghi
3  4  444  xyz

In [17]:
cols = ['col1', 'col2', 'col3']
df = pd.DataFrame(data,columns = ['col1', 'col2', 'col3'])
df
#df.dtypes

   col1  col2 col3
0     1   444  abc
1     2   555  def
2     3   666  ghi
3     4   444  xyz

In [18]:
#cols = ['id', 'sal']
#df[cols] = df[cols].astype('category')
df.dtypes #check from the slides

col1    int64
col2    int64
col3      str
dtype: object

In [ ]:
#df.head(2) #check from the lect slides

NameError: name 'df' is not defined